package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val GeometricBackground = Color(0xFFFDF8F6)
val GeometricSurface = Color(0xFFFFFBFF)
val GeometricSurfaceVariant = Color(0xFFF3EDF7)
val GeometricSurfaceVariantExpanded = Color(0xFFF7F2FA)
val GeometricPrimary = Color(0xFF6750A4)
val GeometricOnPrimary = Color(0xFFFFFFFF)
val GeometricError = Color(0xFFB00020)
val GeometricOnError = Color(0xFFFFFFFF)
val GeometricIncome = Color(0xFF2E7D32)
val GeometricIncomeBg = Color(0xFFDCFCE7) 
val GeometricIncomeText = Color(0xFF166534)
val GeometricExpense = Color(0xFFB00020)
val GeometricExpenseBg = Color(0xFFFEE2E2)
val GeometricExpenseText = Color(0xFF991B1B)
val GeometricOnSurface = Color(0xFF1D1B20)
val GeometricOnSurfaceVariant = Color(0xFF49454F)
val GeometricOutline = Color(0xFF79747E)

val DarkBackground = Color(0xFF121212)
val DarkSurface = Color(0xFF1E1E1E)
val DarkSurfaceVariant = Color(0xFF2D2D2D)
val DarkPrimary = Color(0xFFD0BCFF)
val DarkOnPrimary = Color(0xFF381E72)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkOutline = Color(0xFF938F99)
